---
version: "3.9"
services:
  student-srv:
    build: 
      context: .
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - students-srv-net
    environment:
      - MYSQL_SERVER=students-db
    depends_on:
      - students-db
  students-db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=directdevops
      - MYSQL_PASSWORD=directdevops
    networks:
      - students-db-net
    volumes:
      - type: volume
        source: students-db
        target: /var/lib/mysql
networks:
  students-srv-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
  students-db-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.102.0/24
volumes:
  students-db:
      

    