version: '3.9'
services:
  students-srv:
    build: 
      context: .
    ports:
      - target: 8080
        published: 8082
        protocol: tcp
        mode: host
  students-db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=sri
      - MYSQL-PASSWORD=sri
      - MYSQL-DATABASE=test

    