---
version: "3.9"
services:
  student-srv:
    build: 
      context: .
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
  students-db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=directdevops
      - MYSQL_PASSWORD=directdevops
      

    